# 2024-01-09 增加内容类型字段
ALTER TABLE `chat_gpt`.`gpt_chat_message` ADD COLUMN `content_type` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '内容类型：text：文字 image : 图片' AFTER `content`;

# 2024-01-20 增加用户开启上下文字段和默认赠送次数
ALTER TABLE `chat_gpt`.`gpt_user` ADD COLUMN `context` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否开启上下文' AFTER `ip`;

ALTER TABLE `chat_gpt`.`gpt_user` MODIFY COLUMN `num` int(11) NULL DEFAULT 0 COMMENT '调用次数' AFTER `context`;

INSERT INTO `chat_gpt`.`sys_config` (`id`, `create_user`, `create_time`, `update_user`, `update_time`, `name`, `config_key`, `config_value`, `type`, `deleted`, `remark`) VALUES (8, 'admin', '2024-01-20 16:34:53', 'admin', '2024-01-20 16:34:53', '是否限制访问Chat', 'sys_chat_master', 'true', 1, 0, '是否无限访问Chat');

# 2024-01-22 增加字典 可直接体会sys_config和sys_dict和sys_dict_type表
# 更新表名gpt_base_config 为sys_base_config
INSERT INTO `chat_gpt`.`sys_dict_type` (`id`, `create_user`, `create_time`, `update_user`, `update_time`, `name`, `type`, `status`, `deleted`) VALUES (16, 'admin', '2024-01-22 09:15:45', 'admin', '2024-01-22 09:15:45', '上传类型', 'sys_oss_type', 1, 0);
INSERT INTO `chat_gpt`.`sys_dict_type` (`id`, `create_user`, `create_time`, `update_user`, `update_time`, `name`, `type`, `status`, `deleted`) VALUES (17, 'admin', '2024-01-22 09:29:29', 'System', '2024-01-22 09:29:29', '短信类型', 'sys_sms_type', 1, 0);
INSERT INTO `chat_gpt`.`sys_dict` (`id`, `create_user`, `create_time`, `update_user`, `update_time`, `label`, `value`, `dict_type`, `css_class`, `list_class`, `is_default`, `sort`, `status`, `deleted`, `remark`) VALUES (41, 'admin', '2024-01-22 09:15:57', 'admin', '2024-01-22 01:45:58', '本地上传', '1', 'sys_oss_type', '', 'primary', 0, 1, 1, 0, '');
INSERT INTO `chat_gpt`.`sys_dict` (`id`, `create_user`, `create_time`, `update_user`, `update_time`, `label`, `value`, `dict_type`, `css_class`, `list_class`, `is_default`, `sort`, `status`, `deleted`, `remark`) VALUES (42, 'admin', '2024-01-22 09:16:46', 'admin', '2024-01-22 01:46:06', '阿里OSS', '2', 'sys_oss_type', '', 'success', 0, 2, 1, 0, '');
INSERT INTO `chat_gpt`.`sys_dict` (`id`, `create_user`, `create_time`, `update_user`, `update_time`, `label`, `value`, `dict_type`, `css_class`, `list_class`, `is_default`, `sort`, `status`, `deleted`, `remark`) VALUES (43, 'admin', '2024-01-22 09:17:06', 'System', '2024-01-22 01:46:06', '腾讯COS', '3', 'sys_oss_type', '', 'warning', 0, 3, 1, 0, '');
INSERT INTO `chat_gpt`.`sys_dict` (`id`, `create_user`, `create_time`, `update_user`, `update_time`, `label`, `value`, `dict_type`, `css_class`, `list_class`, `is_default`, `sort`, `status`, `deleted`, `remark`) VALUES (44, 'admin', '2024-01-22 09:30:24', 'System', '2024-01-22 09:30:24', '阿里云SMS', '1', 'sys_sms_type', '', 'primary', 0, 1, 1, 0, '');
INSERT INTO `chat_gpt`.`sys_dict` (`id`, `create_user`, `create_time`, `update_user`, `update_time`, `label`, `value`, `dict_type`, `css_class`, `list_class`, `is_default`, `sort`, `status`, `deleted`, `remark`) VALUES (45, 'admin', '2024-01-22 09:30:37', 'System', '2024-01-22 09:30:37', '腾讯云SMS', '2', 'sys_sms_type', '', 'success', 0, 2, 1, 0, '');
INSERT INTO `chat_gpt`.`sys_dict` (`id`, `create_user`, `create_time`, `update_user`, `update_time`, `label`, `value`, `dict_type`, `css_class`, `list_class`, `is_default`, `sort`, `status`, `deleted`, `remark`) VALUES (46, 'admin', '2024-01-22 15:37:59', 'System', '2024-01-22 15:37:59', '文心一言', 'WENXIN', 'gpt_model_type', '', 'success', 0, 2, 1, 0, '');
INSERT INTO `chat_gpt`.`sys_dict` (`id`, `create_user`, `create_time`, `update_user`, `update_time`, `label`, `value`, `dict_type`, `css_class`, `list_class`, `is_default`, `sort`, `status`, `deleted`, `remark`) VALUES (47, 'admin', '2024-01-22 15:38:17', 'System', '2024-01-22 15:38:17', '通义千问', 'QIANWEN', 'gpt_model_type', '', 'info', 0, 3, 1, 0, '');
INSERT INTO `chat_gpt`.`sys_dict` (`id`, `create_user`, `create_time`, `update_user`, `update_time`, `label`, `value`, `dict_type`, `css_class`, `list_class`, `is_default`, `sort`, `status`, `deleted`, `remark`) VALUES (48, 'admin', '2024-01-22 15:38:34', 'System', '2024-01-22 15:38:34', '讯飞星火', 'SPARK', 'gpt_model_type', '', 'warning', 0, 4, 1, 0, '');
INSERT INTO `chat_gpt`.`sys_dict` (`id`, `create_user`, `create_time`, `update_user`, `update_time`, `label`, `value`, `dict_type`, `css_class`, `list_class`, `is_default`, `sort`, `status`, `deleted`, `remark`) VALUES (49, 'admin', '2024-01-22 15:39:03', 'admin', '2024-01-22 15:39:03', '智谱清言', 'ZHIPU', 'gpt_model_type', '', 'danger', 0, 5, 1, 0, '');